name: Build Linux app
on:
  # release:
    # types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          git checkout -b build/linux &&
          npm install &&
          npm run build:linux &&
          rm .gitignore &&
          cd dist &&
          zip tool3rd-linux.zip tool3rd*.deb tool3rd*.snap tool3rd*.AppImage -s 64m &&
          git add tool3rd-linux.z* &&
          git config user.name "Seokseong Jeon"
          git config user.email "sjeon87@gmail.com'
          git commit -m "Linux app" &&
          git push origin build/linux
