name: Build macOS app
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - run: |
          git checkout -b build/macos &&
          npm install &&
          npm run build:mac &&
          mv .gitignore .nogitignore &&
          git add out &&
          mv .nogitignore .gitignore &&
          git commit -m "macOS app" &&
          git push origin build/macos
